//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.SalesPersonServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesPersonServiceReference.ISalesPersonSVC")]
    public interface ISalesPersonSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/GetOrderHeaders", ReplyAction="http://tempuri.org/ISalesPersonSVC/GetOrderHeadersResponse")]
        OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[] GetOrderHeaders(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/GetOrderHeaders", ReplyAction="http://tempuri.org/ISalesPersonSVC/GetOrderHeadersResponse")]
        System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[]> GetOrderHeadersAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/GetAllOrderHeaders", ReplyAction="http://tempuri.org/ISalesPersonSVC/GetAllOrderHeadersResponse")]
        OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[] GetAllOrderHeaders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/GetAllOrderHeaders", ReplyAction="http://tempuri.org/ISalesPersonSVC/GetAllOrderHeadersResponse")]
        System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[]> GetAllOrderHeadersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/GetOrderDetails", ReplyAction="http://tempuri.org/ISalesPersonSVC/GetOrderDetailsResponse")]
        OnlineStore.Infrastructure.Business.DTO.SalesProductDTO GetOrderDetails(int purchaseOrderHeaderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/GetOrderDetails", ReplyAction="http://tempuri.org/ISalesPersonSVC/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.SalesProductDTO> GetOrderDetailsAsync(int purchaseOrderHeaderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/CreateShipmentXML", ReplyAction="http://tempuri.org/ISalesPersonSVC/CreateShipmentXMLResponse")]
        void CreateShipmentXML(int purchaseOrderHeaderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesPersonSVC/CreateShipmentXML", ReplyAction="http://tempuri.org/ISalesPersonSVC/CreateShipmentXMLResponse")]
        System.Threading.Tasks.Task CreateShipmentXMLAsync(int purchaseOrderHeaderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesPersonSVCChannel : OnlineStore.SalesPersonServiceReference.ISalesPersonSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesPersonSVCClient : System.ServiceModel.ClientBase<OnlineStore.SalesPersonServiceReference.ISalesPersonSVC>, OnlineStore.SalesPersonServiceReference.ISalesPersonSVC {
        
        public SalesPersonSVCClient() {
        }
        
        public SalesPersonSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesPersonSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesPersonSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesPersonSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[] GetOrderHeaders(string userId) {
            return base.Channel.GetOrderHeaders(userId);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[]> GetOrderHeadersAsync(string userId) {
            return base.Channel.GetOrderHeadersAsync(userId);
        }
        
        public OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[] GetAllOrderHeaders() {
            return base.Channel.GetAllOrderHeaders();
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[]> GetAllOrderHeadersAsync() {
            return base.Channel.GetAllOrderHeadersAsync();
        }
        
        public OnlineStore.Infrastructure.Business.DTO.SalesProductDTO GetOrderDetails(int purchaseOrderHeaderID) {
            return base.Channel.GetOrderDetails(purchaseOrderHeaderID);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.SalesProductDTO> GetOrderDetailsAsync(int purchaseOrderHeaderID) {
            return base.Channel.GetOrderDetailsAsync(purchaseOrderHeaderID);
        }
        
        public void CreateShipmentXML(int purchaseOrderHeaderID) {
            base.Channel.CreateShipmentXML(purchaseOrderHeaderID);
        }
        
        public System.Threading.Tasks.Task CreateShipmentXMLAsync(int purchaseOrderHeaderID) {
            return base.Channel.CreateShipmentXMLAsync(purchaseOrderHeaderID);
        }
    }
}
