//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.AccountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountServiceReference.IAccountSVC")]
    public interface IAccountSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSVC/CreatePerson", ReplyAction="http://tempuri.org/IAccountSVC/CreatePersonResponse")]
        void CreatePerson(OnlineStore.Infrastructure.Business.DTO.PersonDTO personDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSVC/CreatePerson", ReplyAction="http://tempuri.org/IAccountSVC/CreatePersonResponse")]
        System.Threading.Tasks.Task CreatePersonAsync(OnlineStore.Infrastructure.Business.DTO.PersonDTO personDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSVC/GetClientOrderHeaders", ReplyAction="http://tempuri.org/IAccountSVC/GetClientOrderHeadersResponse")]
        OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[] GetClientOrderHeaders(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountSVC/GetClientOrderHeaders", ReplyAction="http://tempuri.org/IAccountSVC/GetClientOrderHeadersResponse")]
        System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[]> GetClientOrderHeadersAsync(string clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountSVCChannel : OnlineStore.AccountServiceReference.IAccountSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountSVCClient : System.ServiceModel.ClientBase<OnlineStore.AccountServiceReference.IAccountSVC>, OnlineStore.AccountServiceReference.IAccountSVC {
        
        public AccountSVCClient() {
        }
        
        public AccountSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreatePerson(OnlineStore.Infrastructure.Business.DTO.PersonDTO personDTO) {
            base.Channel.CreatePerson(personDTO);
        }
        
        public System.Threading.Tasks.Task CreatePersonAsync(OnlineStore.Infrastructure.Business.DTO.PersonDTO personDTO) {
            return base.Channel.CreatePersonAsync(personDTO);
        }
        
        public OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[] GetClientOrderHeaders(string clientId) {
            return base.Channel.GetClientOrderHeaders(clientId);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.OrderHeaderDTO[]> GetClientOrderHeadersAsync(string clientId) {
            return base.Channel.GetClientOrderHeadersAsync(clientId);
        }
    }
}
