//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.CartStoreServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CartStoreServiceReference.ICartSVC")]
    public interface ICartSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/AddItem", ReplyAction="http://tempuri.org/ICartSVC/AddItemResponse")]
        void AddItem(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/AddItem", ReplyAction="http://tempuri.org/ICartSVC/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/SubstractQtyItem", ReplyAction="http://tempuri.org/ICartSVC/SubstractQtyItemResponse")]
        void SubstractQtyItem(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/SubstractQtyItem", ReplyAction="http://tempuri.org/ICartSVC/SubstractQtyItemResponse")]
        System.Threading.Tasks.Task SubstractQtyItemAsync(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/RemoveLine", ReplyAction="http://tempuri.org/ICartSVC/RemoveLineResponse")]
        void RemoveLine(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/RemoveLine", ReplyAction="http://tempuri.org/ICartSVC/RemoveLineResponse")]
        System.Threading.Tasks.Task RemoveLineAsync(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/ComputeTotalQuantity", ReplyAction="http://tempuri.org/ICartSVC/ComputeTotalQuantityResponse")]
        int ComputeTotalQuantity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/ComputeTotalQuantity", ReplyAction="http://tempuri.org/ICartSVC/ComputeTotalQuantityResponse")]
        System.Threading.Tasks.Task<int> ComputeTotalQuantityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/ComputeTotalValue", ReplyAction="http://tempuri.org/ICartSVC/ComputeTotalValueResponse")]
        decimal ComputeTotalValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/ComputeTotalValue", ReplyAction="http://tempuri.org/ICartSVC/ComputeTotalValueResponse")]
        System.Threading.Tasks.Task<decimal> ComputeTotalValueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/Clear", ReplyAction="http://tempuri.org/ICartSVC/ClearResponse")]
        void Clear();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/Clear", ReplyAction="http://tempuri.org/ICartSVC/ClearResponse")]
        System.Threading.Tasks.Task ClearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/Lines", ReplyAction="http://tempuri.org/ICartSVC/LinesResponse")]
        OnlineStore.Infrastructure.Business.DTO.CartLineDTO[] Lines();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartSVC/Lines", ReplyAction="http://tempuri.org/ICartSVC/LinesResponse")]
        System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.CartLineDTO[]> LinesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICartSVCChannel : OnlineStore.CartStoreServiceReference.ICartSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartSVCClient : System.ServiceModel.ClientBase<OnlineStore.CartStoreServiceReference.ICartSVC>, OnlineStore.CartStoreServiceReference.ICartSVC {
        
        public CartSVCClient() {
        }
        
        public CartSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddItem(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity) {
            base.Channel.AddItem(productDto, quantity);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity) {
            return base.Channel.AddItemAsync(productDto, quantity);
        }
        
        public void SubstractQtyItem(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity) {
            base.Channel.SubstractQtyItem(productDto, quantity);
        }
        
        public System.Threading.Tasks.Task SubstractQtyItemAsync(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto, int quantity) {
            return base.Channel.SubstractQtyItemAsync(productDto, quantity);
        }
        
        public void RemoveLine(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto) {
            base.Channel.RemoveLine(productDto);
        }
        
        public System.Threading.Tasks.Task RemoveLineAsync(OnlineStore.Infrastructure.Business.DTO.ProductDTO productDto) {
            return base.Channel.RemoveLineAsync(productDto);
        }
        
        public int ComputeTotalQuantity() {
            return base.Channel.ComputeTotalQuantity();
        }
        
        public System.Threading.Tasks.Task<int> ComputeTotalQuantityAsync() {
            return base.Channel.ComputeTotalQuantityAsync();
        }
        
        public decimal ComputeTotalValue() {
            return base.Channel.ComputeTotalValue();
        }
        
        public System.Threading.Tasks.Task<decimal> ComputeTotalValueAsync() {
            return base.Channel.ComputeTotalValueAsync();
        }
        
        public void Clear() {
            base.Channel.Clear();
        }
        
        public System.Threading.Tasks.Task ClearAsync() {
            return base.Channel.ClearAsync();
        }
        
        public OnlineStore.Infrastructure.Business.DTO.CartLineDTO[] Lines() {
            return base.Channel.Lines();
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Infrastructure.Business.DTO.CartLineDTO[]> LinesAsync() {
            return base.Channel.LinesAsync();
        }
    }
}
