//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.OrderProcessorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderProcessorServiceReference.IOrderProcessorSVC")]
    public interface IOrderProcessorSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessorSVC/ProcessOrder", ReplyAction="http://tempuri.org/IOrderProcessorSVC/ProcessOrderResponse")]
        void ProcessOrder(OnlineStore.Infrastructure.Business.DTO.CartLineDTO[] cart, OnlineStore.Infrastructure.Business.DTO.ShippingDetailsDTO shippingDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProcessorSVC/ProcessOrder", ReplyAction="http://tempuri.org/IOrderProcessorSVC/ProcessOrderResponse")]
        System.Threading.Tasks.Task ProcessOrderAsync(OnlineStore.Infrastructure.Business.DTO.CartLineDTO[] cart, OnlineStore.Infrastructure.Business.DTO.ShippingDetailsDTO shippingDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderProcessorSVCChannel : OnlineStore.OrderProcessorServiceReference.IOrderProcessorSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderProcessorSVCClient : System.ServiceModel.ClientBase<OnlineStore.OrderProcessorServiceReference.IOrderProcessorSVC>, OnlineStore.OrderProcessorServiceReference.IOrderProcessorSVC {
        
        public OrderProcessorSVCClient() {
        }
        
        public OrderProcessorSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderProcessorSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessorSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessorSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessOrder(OnlineStore.Infrastructure.Business.DTO.CartLineDTO[] cart, OnlineStore.Infrastructure.Business.DTO.ShippingDetailsDTO shippingDetails) {
            base.Channel.ProcessOrder(cart, shippingDetails);
        }
        
        public System.Threading.Tasks.Task ProcessOrderAsync(OnlineStore.Infrastructure.Business.DTO.CartLineDTO[] cart, OnlineStore.Infrastructure.Business.DTO.ShippingDetailsDTO shippingDetails) {
            return base.Channel.ProcessOrderAsync(cart, shippingDetails);
        }
    }
}
